---
 
- name: Send kickstart file
  hosts: ftds01
  tasks:
    - name: kickstart file
      copy:
        src: "./conf/kickstart/{{ item }}"
        dest: /srv/www/htdocs/ks/
      loop:
#RHEL7.9
        - test02.ks
        - test03.ks
#RHEL8.4
        - ftgfs01.ks
        - ftgfs02.ks
        - ftgfs03.ks

